defaults:
  - _self_
  - data: data
  - resample: resample
  - datamodule: datamodule
  - transforms: transforms
  - model: model
  - criterion_params: criterion_params
  - optimizer_params: optimizer_params
  - scheduler_params: scheduler_params
  - stores: stores


hydra:
  run:
    dir: outputs/${stores.project_name}/${stores.unique_id}