image_size: 32
mean:
- 0.485
- 0.456
- 0.406
std:
- 0.229
- 0.224
- 0.225
mixup: false
mixup_params: null
train_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToPILImage
    - _target_: torchvision.transforms.RandomResizedCrop
      size: ${transforms.image_size}
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: ${transforms.mean}
      std: ${transforms.std}
valid_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToPILImage
    - _target_: torchvision.transforms.Resize
      size: ${transforms.image_size}
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: ${transforms.mean}
      std: ${transforms.std}
test_transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.ToPILImage
    - _target_: torchvision.transforms.Resize
      size: ${transforms.image_size}
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean: ${transforms.mean}
      std: ${transforms.std}